name: Release Merge Trigger

on:
  push:
    branches:
      - rc
      - main
    paths-ignore:
      - '*.md'
      - 'webapp/*.md'
      - '*.png'
      - '.github/**'
      - 'LICENSE'
      - '.env.sample'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install semver
        run: npm install -g semver

      - name: Release Minor Version
        if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, '[release]:')
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          LATEST_VERSION=$(gh release list --exclude-drafts -L 1 | awk {'print $3'})
          semver $LATEST_VERSION || (echo "latest release is not in valid semantic version format: ${LATEST_VERSION}" && exit 1)
          MINOR_BUMP_VERSION=$(semver $LATEST_VERSION -i minor)
          gh workflow run release.yml -f version=$MINOR_BUMP_VERSION
          # gh run watch $RUN_ID --exit-status

      - name: Release Candidate Version
        if: github.ref == 'refs/heads/rc'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          LATEST_VERSION=$(gh release list --exclude-drafts -L 1 | awk {'print $3'})
          semver $LATEST_VERSION || (echo "latest release is not in valid semantic version format: ${LATEST_VERSION}" && exit 1)
          NEW_VERSION=""
          if [[ $LATEST_VERSION == *"-rc."* ]]; then
            NEW_VERSION=$(semver $LATEST_VERSION --preid rc -i prerelease)
          else
            NEW_VERSION="$(semver $LATEST_VERSION -i minor)-rc.0"
          fi

          gh workflow run release.yml -f version=$NEW_VERSION
          # gh run watch $RUN_ID --exit-status
